export const QUARTIERI = [
    'INTRODUZIONE',
    'CONTROLLO_INTERFERENZA',
    'INIBIZIONE_RISPOSTA',
    'MEMORIA_LAVORO',
    'FLESSIBILITA_COGNITIVA',
    'MEDIA_LITERACY'
];

export const QUARTIERE = {
    INTRODUZIONE: 'INTRODUZIONE',
    CONTROLLO_INTERFERENZA: 'CONTROLLO_INTERFERENZA',
    INIBIZIONE_RISPOSTA: 'INIBIZIONE_RISPOSTA',
    MEMORIA_LAVORO: 'MEMORIA_LAVORO',
    FLESSIBILITA_COGNITIVA: 'FLESSIBILITA_COGNITIVA',
    MEDIA_LITERACY: 'MEDIA_LITERACY'
};

export const QUARTIERE_LABEL: any = {
    INTRODUZIONE: 'Introduzione (Coding)',
    CONTROLLO_INTERFERENZA: "Controllo Interferenza",
    INIBIZIONE_RISPOSTA: 'Inibizione Risposta',
    MEMORIA_LAVORO: 'Memoria di Lavoro',
    FLESSIBILITA_COGNITIVA: 'Flessibilità Cognitiva',
    MEDIA_LITERACY: 'Media Literacy'
};